version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fleet-service-php
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/fleet?serverVersion=16&charset=utf8"
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    container_name: fleet-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: fleet-service-db
    restart: always
    environment:
      POSTGRES_DB: fleet
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
